### ISSUE TITLE
check status

### ISSUE THREAD

**Issue by RobertDWhite** [tarfeef101/raptoreum_miner_docker#2]
Hello,
thanks for this container. what is your recommended method for checking the status of the miner in the container?
Thanks

**Comment by tarfeef101** [comment]
Most pools will offer you a method to view information about the rigs you've hooked up to it. The logs will also contain the output of the container (`docker-compose logs mining`).

Otherwise, I might add a basic healthcheck to the container that'll check to see if the script has exited, though that's not meaningfully better than just seeing if the container exited or not. You're probably better off looking at CPU usage on the host, in a manner similar to how I handle the `ethminer` randomly segfaulting but not exiting if you're concerned about the process stalling [gist here](https://gist.github.com/tarfeef101/1721dfabf0a2d6c559925b0b9f2d31a0)

**Comment by tarfeef101** [comment]
added a healthcheck in 52f86fedd196a0ad0e2eeb7d12410a233a04eb8b
