### ISSUE TITLE
Large Page & MSR support

### ISSUE THREAD

**Issue by milesian01** [tarfeef101/raptoreum_miner_docker#5]
Any chance something can be done about Large Page and MSR support in the container?  And on a Windows host, gulp?

**Comment by tarfeef101** [comment]
For large page support, on windows, no. That's enabled via a settings menu in windows, docker containers (which run in a Linux VM) just have no ability to interact with that system. I'm not entirely sure if the VM bypasses the windows kernel to enough of a degree to be able to address the memory outside of windows memory management, that'd require a lot of windows kernel changes to make possible. Considering they've not said they're doing that, I don't think that's the case (maybe someone has proven or disproven this, idk). 

w/ respect to MSR, to enable kernel modules, etc. you'd need to run the container in privileged mode, since you'd need the host to be able to pass that info along. I personally feel that's something that is a bit antithetical to the idea of how containers should operate, if those are features you really want, you're probably running a dedicated mining rig and should be more okay with running the app on bare metal and making system-level changes in the process than someone running on a machine which pulls double-or-more duty with other tasks (like me, which is why I made this, primarily). 

So hopefully that's not too disappointing of an answer, but it's the answer I've got for you.
